# Tested: 2024/08/05
# by Kasper Arfman
name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #N.B. Openjdk comes pre-installed, so it is left out here
      - name: Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake
          pip install --user --upgrade Cython virtualenv
          pip install --user --upgrade buildozer

      # Check if buildozer still requires openjdk version 17.
      # https://buildozer.readthedocs.io/en/latest/installation.html
      - name: Build APK
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          yes | buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk