name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: '30.0.3'
        components: |
          platform-tools
          platforms;android-30
          build-tools;30.0.3

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3-setuptools \
          python3-dev \
          zip \
          zlib1g-dev \
          libncurses5-dev \
          libffi-dev \
          libgmp-dev \
          libssl-dev \
          liblzma-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          openjdk-11-jdk \
          wget \
          curl \
          patch

    - name: Install Buildozer and pip dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Build the APK
      run: |
        buildozer android debug
