name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the APK
      run: |

        pip install buildozer
        sudo apt update
        sudo apt install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev
        pip install cython==0.29.34

        yes | buildozer android debug --log_level=3

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-apk
        path: bin/*.apk