name: Build4 APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove preinstalled JDKs
        run: |
          sudo rm -rf /usr/lib/jvm/temurin-8*
          sudo rm -rf /usr/lib/jvm/temurin-11*
          sudo rm -rf /usr/lib/jvm/temurin-21*
          ls /usr/lib/jvm
          java -version

      - name: Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake
          pip install --user --upgrade Cython virtualenv
          pip install --user --upgrade buildozer
          export PATH=$PATH:~/.local/bin/



          
      # - name: Handle Java path
      #   run: |
      #     JAVA_HOME_PATH="/usr/lib/jvm/temurin-17-jdk-amd64"

      #     sudo update-java-alternatives --set ${JAVA_HOME_PATH}

      #     # Backup the original ~/.bashrc file
      #     cp ~/.bashrc ~/.bashrc.bak

      #     # Check if JAVA_HOME is already set in the file
      #     if grep -q "export JAVA_HOME=" ~/.bashrc; then
      #         # Update the existing JAVA_HOME line
      #         sed -i "s|export JAVA_HOME=.*|export JAVA_HOME=${JAVA_HOME_PATH}|g" ~/.bashrc
      #     else
      #         # Append the JAVA_HOME setting to the end of the file
      #         echo "export JAVA_HOME=${JAVA_HOME_PATH}" >> ~/.bashrc
      #     fi

      #     # Apply the changes to the current session
      #     export JAVA_HOME=${JAVA_HOME_PATH}
      #     source ~/.bashrc

      #     # Verify the change
      #     echo "JAVA_HOME is set to: $JAVA_HOME"
      #     java -version
      #     javac -version

      #     ls /usr/lib/jvm

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'

      - name: Build with Buildozer
        run: |
          yes | buildozer -v android debug

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: package
      #     path: bin/*.apk