name: Build3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64


    - name: Install Dependencies
      run: |
        sudo apt update

        # remove java
        sudo apt-get purge openjdk-\* icedtea-\* icedtea6-\*


        sudo apt install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          automake
        export PATH=$PATH:~/.local/bin/
        pip install --upgrade cython
        pip3 install --user --upgrade buildozer


    - name: Java status
      run: |
        archlinux-java status
        sudo archlinux-java set java-17-openjdk


    - name: Appclean
      run: |
        buildozer appclean

    - name: Build the APK
      run: |
        yes | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-apk
        path: bin/*.apk