name: Build5 APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Remove preinstalled JDKs
      #   run: |
      #     JAVA_HOME_PATH="/usr/lib/jvm/temurin-17-jdk-amd64"
      #     sudo update-java-alternatives --set ${JAVA_HOME_PATH}
      #     sudo rm -rf /usr/lib/jvm/temurin-8*
      #     sudo rm -rf /usr/lib/jvm/temurin-11*
      #     sudo rm -rf /usr/lib/jvm/temurin-21*
      #     ls /usr/lib/jvm
      #     java -version

      # - name: Buildozer dependencies
      #   run: |
      #     sudo apt update
      #     sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake
      #     pip install --user --upgrade Cython virtualenv
      #     pip install --user --upgrade buildozer
      #     # export PATH=$PATH:~/.local/bin/
      #     echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc

      - name: Handle Java path
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH

          echo "JAVA_HOME is set to: $JAVA_HOME"
          java -version
          javac -version
          ls /usr/lib/jvm
          printenv | grep JAVA_HOME

      - name: Check Again
        run: |
          echo "JAVA_HOME is set to: $JAVA_HOME"
          java -version
          javac -version
          ls /usr/lib/jvm
          printenv | grep JAVA_HOME

      # - name: Build with Buildozer
      #   run: |
      #     yes | buildozer -v android debug

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: package
      #     path: bin/*.apk