name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Kivy Build APK Action
        uses: ./   # use Kasper-Arfman/kivy-build-apk@main
        with:
          example-input: 'some-value'
